[package]
name = "libfyaml-sys"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
description = "Rust binding for libfyaml"
documentation = "https://docs.rs/libfyaml-sys"
edition = "2021"
license = "MIT"
links = "libfyaml"
repository = "https://github.com/dtolnay/libfyaml-rs"
rust-version = "1.63"

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.63"
cc = "1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
